forklift_model:
  joint_state_controller:
    type: joint_state/JointStateController
    publish_rate: 20


  steering_controller:
    type: effort_controller/JointPositionController
    joint: base_joint
    pid: {p: 1.0, i: 1.0, d: 1.0}
